[package]
name = "xoroshiro"
version = "1.0.0"
cairo-version = "2.0.0"
authors = ["Milan Cermak"]
description = "Pseudo-random number generator"
readme = "README.md"
repository = "https://github.com/milancermak/xoroshiro-cairo"
license-file = "LICENSE"
keywords = ["random", "randomness", "prng", "cairo", "starknet", "game"]

[dependencies]
starknet = ">=2.0.0"

[lib]

[[target.starknet-contract]]
sierra = true
