name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: software-mansion/setup-scarb@v1
      - run: scarb fmt --check
      - run: scarb build

      - uses: foundry-rs/setup-snfoundry@v3
      - run: snforge test
