name: Test
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # - name: Rust setup
      #   uses: dtolnay/rust-toolchain@stable

      # - name: Rust setup
      #   uses: actions-rs/toolchain@v1
      #   with:
      #     toolchain: stable

      - name: Install Scarb
        uses: ./.github/actions/scarb
        # with:
        #   version: '0.4.0'

      - name: Run test
        run: scarb test
